export interface Waifu {
  id: number
  name: string
  image: string
}

export const waifuData: Waifu[] = [
  { id: 1, name: "Speedwagon (Jojo's Bizarre Adventure)", image: "https://cdn.susmanga.com/waifu/1.jpg" },
  { id: 2, name: "Maomao (The Apothecary Diaries)", image: "https://cdn.susmanga.com/waifu/2.jpg" },
  { id: 3, name: "Alina Clover (I May Be a Guild Receptionist…)", image: "https://cdn.susmanga.com/waifu/3.jpg" },
  { id: 4, name: "Nico Wakatsuki (Witch Watch)", image: "https://cdn.susmanga.com/waifu/4.jpg" },
  { id: 5, name: "Anne Shirley (Anne of Green Gables)", image: "https://cdn.susmanga.com/waifu/5.jpg" },
  { id: 6, name: "Reiko Kujirai (Kowloon Generic Romance)", image: "https://cdn.susmanga.com/waifu/6.jpg" },
  { id: 7, name: "Takao Ameko (Doctor Detective)", image: "https://cdn.susmanga.com/waifu/7.jpg" },
  { id: 8, name: "Oka Shiunji (Shiunji Family Children)", image: "https://cdn.susmanga.com/waifu/8.jpg" },
  { id: 9, name: "Oguri Cap (Uma Musume: Cinderella Gray)", image: "https://cdn.susmanga.com/waifu/9.jpg" },
  { id: 10, name: "Yor Forger (Spy × Family)", image: "https://cdn.susmanga.com/waifu/10.jpg" },
  { id: 11, name: "Marin Kitagawa (My Dress-Up Darling)", image: "https://cdn.susmanga.com/waifu/11.jpg" },
  { id: 12, name: "Hayase Nagatoro (Don’t Toy With Me, Miss Nagatoro 2)", image: "https://cdn.susmanga.com/waifu/12.jpg" },
  { id: 13, name: "Tomo Aizawa (Tomo‑chan Is a Girl!)", image: "https://cdn.susmanga.com/waifu/13.jpg" },
  { id: 14, name: "Mikasa Ackerman (Attack on Titan)", image: "https://cdn.susmanga.com/waifu/14.jpg" },
  { id: 15, name: "Mahiru Shiina (The Angel Next Door Spoils Me Rotten)", image: "https://cdn.susmanga.com/waifu/15.jpg" },
  { id: 16, name: "Anna Yanami (Too Many Losing Heroines!)", image: "https://cdn.susmanga.com/waifu/16.jpg" },
  { id: 17, name: "Frieren (Frieren: Beyond Journey’s End)", image: "https://cdn.susmanga.com/waifu/17.jpg" },
  { id: 18, name: "Übel (Frieren)", image: "https://cdn.susmanga.com/waifu/18.jpg" },
  { id: 19, name: "Minami Nanami (Bottom‑tier Character Tomozaki 2)", image: "https://cdn.susmanga.com/waifu/19.jpg" },
  { id: 20, name: "Suzune Horikita (Classroom of the Elite S3)", image: "https://cdn.susmanga.com/waifu/20.jpg" },
  { id: 21, name: "Rem (Re:Zero)", image: "https://cdn.susmanga.com/waifu/21.jpg" },
  { id: 22, name: "Zero Two (Darling in the Franxx)", image: "https://cdn.susmanga.com/waifu/22.jpg" },
  { id: 23, name: "Makima (Chainsaw Man)", image: "https://cdn.susmanga.com/waifu/23.jpg" },
  { id: 24, name: "Kurumi Tokisaki (Date A Live)", image: "https://cdn.susmanga.com/waifu/24.jpg" },
  { id: 25, name: "Roronoa Zoro (One Piece)", image: "https://cdn.susmanga.com/waifu/25.jpg" },
  { id: 26, name: "Mai Sakurajima (Rascal Does Not Dream…)", image: "https://cdn.susmanga.com/waifu/26.jpg" },
  { id: 27, name: "Holo (Spice and Wolf)", image: "https://cdn.susmanga.com/waifu/27.jpg" },
  { id: 28, name: "Kurisu Makise (Steins;Gate)", image: "https://cdn.susmanga.com/waifu/28.jpg" },
  { id: 29, name: "Hitagi Senjougahara (Bakemonogatari)", image: "https://cdn.susmanga.com/waifu/29.jpg" },
  { id: 30, name: "Rin Tohsaka (Fate/stay night)", image: "https://cdn.susmanga.com/waifu/30.jpg" },
  { id: 31, name: "Kaguya Shinomiya (Kaguya‑sama: Love Is War)", image: "https://cdn.susmanga.com/waifu/31.jpg" },
  { id: 32, name: "Shinobu Oshino (Monogatari series)", image: "https://cdn.susmanga.com/waifu/32.jpg" },
  { id: 33, name: "Ai Hayasaka (Kaguya‑sama)", image: "https://cdn.susmanga.com/waifu/33.jpg" },
  { id: 34, name: "Megumin (KonoSuba)", image: "https://cdn.susmanga.com/waifu/34.jpg" },
  { id: 35, name: "Vladilena Milize (86)", image: "https://cdn.susmanga.com/waifu/35.jpg" },
  { id: 36, name: "Mikoto Misaka (A Certain Scientific Railgun)", image: "https://cdn.susmanga.com/waifu/36.jpg" },
  { id: 37, name: "Darkness (Konosuba)", image: "https://cdn.susmanga.com/waifu/37.jpg" },
  { id: 38, name: "Chisato Nishikigi (Lycoris Recoil)", image: "https://cdn.susmanga.com/waifu/38.jpg" },
  { id: 39, name: "Emilia (Re:Zero) ", image: "https://cdn.susmanga.com/waifu/39.jpg" },
  { id: 40, name: "Kumiko Oumae (Sound! Euphonium)", image: "https://cdn.susmanga.com/waifu/40.jpg" },
  { id: 41, name: "Aqua (Konosuba)", image: "https://cdn.susmanga.com/waifu/41.jpg" },
  { id: 42, name: "Kana Arima (Oshi no Ko)", image: "https://cdn.susmanga.com/waifu/42.jpg" },
  { id: 43, name: "Tohru Honda (Fruits Basket)", image: "https://cdn.susmanga.com/waifu/43.jpg" },
  { id: 44, name: "Saber (Fate/stay night)", image: "https://cdn.susmanga.com/waifu/44.jpg" },
  { id: 45, name: "Ochaco Uraraka (My Hero Academia)", image: "https://cdn.susmanga.com/waifu/45.jpg" },
  { id: 46, name: "Nami (One Piece)", image: "https://cdn.susmanga.com/waifu/46.jpg" },
  { id: 47, name: "Erza Scarlet (Fairy Tail)", image: "https://cdn.susmanga.com/waifu/47.jpg" },
  { id: 48, name: "Rukia Kuchiki (Bleach)", image: "https://cdn.susmanga.com/waifu/48.jpg" },
  { id: 49, name: "Lucy Heartfilia (Fairy Tail) ", image: "https://cdn.susmanga.com/waifu/49.jpg" },
  { id: 50, name: "Asuna Yuuki (Sword Art Online)", image: "https://cdn.susmanga.com/waifu/50.jpg" },
]
